### ISSUE TITLE
Decoding Json Error Resulting in Unclosed Connector

### ISSUE THREAD

**Issue by cocoon333** [circleguard/ossapi#60]
![image](https://user-images.githubusercontent.com/15187455/230505975-18c95578-1e05-4f77-b48d-c83ad077c4f4.png)

Unfortunately, I cannot reproduce this error. It just happens once in a while when I am requesting user profiles.

**Comment by cocoon333** [comment]
The error generally occurs in clusters though, so possibly caused by network problems?

**Comment by Stedoss** [comment]
Most likely the osu! API being flaky returning errors in plaintext. Unsure if it's worth adding a mimetype check before decoding to JSON to avoid uncaught exceptions?

**Comment by tybug** [comment]
I haven't seen this error before, which makes me think it's async-specific. On inspecting source code it seems that requests and aiohttp differ in how they handle json decoding: requests decodes regardless of mimetype (making appropriate guesses), and aiohttp throws by default.

It is possible the returned value here is a plaintext error, but it's also possible it's a normal json response with a differing mimetype. Even if this is an osu-web issue, I'd prefer to match sync behavior in all possible cases.

I've disabled throw-on-invalidate-mimetype in cf56b0bd2e048027701da353d73dea347e15d405 in the hopes that fixes this. Please reopen if it doesn't.

**Comment by cocoon333** [comment]
Unfortunately, the same error is still coming up.

**Comment by tybug** [comment]
Hmm. I'd need to see the actual response to figure out what to do here. If you're hammering the api, it's possible you're hitting a ratelimit response that I've never seen before.

**Comment by cocoon333** [comment]
![Screenshot from 2023-04-08 17-13-41](https://user-images.githubusercontent.com/15187455/230750480-26744045-e02a-417d-a5b8-1b5f3fc4772a.png)

Screenshot of more detailed error message

**Comment by tybug** [comment]
As an update, I hammered the api until I got a ratelimit error and can confirm it's returned as valid json:

```
...
  File "/Users/tybug/Desktop/Liam/coding/osu/ossapi/ossapi/ossapiv2_async.py", line 2428, in user
    return await self._get(User, f"/users/{user}/{mode.value if mode else ''}",
  File "/Users/tybug/Desktop/Liam/coding/osu/ossapi/ossapi/ossapiv2_async.py", line 637, in _get
    return await self._request(type_, "GET", url, params=params)
  File "/Users/tybug/Desktop/Liam/coding/osu/ossapi/ossapi/ossapiv2_async.py", line 624, in _request
    self._check_response(json_, url)
  File "/Users/tybug/Desktop/Liam/coding/osu/ossapi/ossapi/ossapiv2_async.py", line 633, in _check_response
    raise ValueError(f"api returned an error of `{json_['error']}` for "
ValueError: api returned an error of `Too Many Attempts.` for a request to https://osu.ppy.sh/api/v2/users/tybug2/
```

So that's not the culprit above.

**Comment by mbalsdon** [comment]
Hi, I'm also seeing this error periodically when I spam the API as hard as my machine can and for long enough.
```
Traceback (most recent call last):
  File "/home/mathew/dev/osu-about-me-graph/main.py", line 28, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/mathew/dev/osu-about-me-graph/main.py", line 13, in main
    mentions_graph, current_to_mentions = await get_mentions(10000)
  File "/home/mathew/dev/osu-about-me-graph/get_mentions.py", line 140, in get_mentions
    users = await fetch_users(osu, user_ids)
  File "/home/mathew/dev/osu-about-me-graph/get_mentions.py", line 115, in fetch_users
    results = await asyncio.gather(*tasks, return_exceptions=False)
  File "/home/mathew/dev/osu-about-me-graph/get_mentions.py", line 79, in fetch_single_user
    user = await osu.user(user_id, mode=ossapi.GameMode.OSU)
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/ossapi/ossapiv2_async.py", line 2985, in user
    return await self._get(
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/ossapi/ossapiv2_async.py", line 883, in _get
    return await self._request(type_, "GET", url, params=params)
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/ossapi/ossapiv2_async.py", line 842, in _request
    json_ = await r.json(encoding=None)
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1277, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 502, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://osu.ppy.sh/api/v2/users/5052899/osu'
```

Definitely the API's fault. I've had similar errors in the past using cpp multithreaded.

Tried to workaround by catching and retrying for `aiohttp.ContentTypeError` but then got a new error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 924, in write
    n = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mathew/dev/osu-about-me-graph/main.py", line 28, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/mathew/dev/osu-about-me-graph/main.py", line 13, in main
    mentions_graph, current_to_mentions = await get_mentions(10000)
  File "/home/mathew/dev/osu-about-me-graph/get_mentions.py", line 141, in get_mentions
    users = await fetch_users(osu, user_ids)
  File "/home/mathew/dev/osu-about-me-graph/get_mentions.py", line 116, in fetch_users
    results = await asyncio.gather(*tasks, return_exceptions=False)
  File "/home/mathew/dev/osu-about-me-graph/get_mentions.py", line 80, in fetch_single_user
    user = await osu.user(user_id, mode=ossapi.GameMode.OSU)
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/ossapi/ossapiv2_async.py", line 2992, in user
    return await self._get(
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/ossapi/ossapiv2_async.py", line 890, in _get
    return await self._request(type_, "GET", url, params=params)
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/ossapi/ossapiv2_async.py", line 812, in _request
    r = await make_request()
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/ossapi/ossapiv2_async.py", line 783, in make_request
    return await self.session.request_async(
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/ossapi/ossapiv2_async.py", line 198, in request_async
    return await session.request(method, url, headers=headers, data=data, **kwargs)
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/aiohttp/client.py", line 728, in _request
    await resp.start(conn)
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1055, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/mathew/dev/osu-about-me-graph/venv/lib/python3.10/site-packages/aiohttp/streams.py", line 668, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
```

Not really familiar with aiohttp/asyncio, I'm guessing it's just some corrupted/bad object state in ossapi, leftover from the original 502? Anyways, I fixed by just catching more errors:

```python
async def fetch_single_user(osu: ossapi.OssapiAsync, user_id: int, counter: ProgressCounter) -> typing.Any:
    retries = 0
    while True:
        try:
            user = await osu.user(user_id, mode=ossapi.GameMode.OSU)

            # Race condition here, but locks are expensive and printing is not critical
            counter.increment()
            counter.print_progress_bar()

            return {
                "current_username": user.username.lower(),
                "previous_usernames": [pu.lower() for pu in user.previous_usernames],
                "about_me": user.page.raw,
                "follower_count": user.follower_count,
                "global_rank": user.statistics.global_rank
            }

        except (ValueError, aiohttp.ContentTypeError, aiohttp.ClientError, aiohttp.ClientOSError, asyncio.TimeoutError) as e:
            error_message = str(e).lower()

            # Exponential backoff if we get 429'ed. (https://en.wikipedia.org/wiki/Exponential_backoff)
            if "too many attempts" in error_message:
                wait_sec = (2 ** retries) + random.random()
                if (wait_sec >= 64):
                    wait_sec = 64 + random.random()

                retries += 1
                await asyncio.sleep(wait_sec)
                continue

            # Skip for other errors - may happen if for example someone gets restricted between the time
            # we grab their ID and the time we grab their data.
            return None
```
